# We install python and packages by ourselves
language: minimal

notifications:
  email: false

os:
    - linux
    - osx

# Test notebooks in parallel
env:
  - NOTEBOOK=frequency_classifier.ipynb
  - NOTEBOOK=logistic_regression.ipynb
  - NOTEBOOK=simple_neural_network.ipynb
  - NOTEBOOK=simple_cnn_lenet.ipynb
  - NOTEBOOK=transfer_learning.ipynb

before_install:
  # Install miniconda based on the OS
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-4.5.12-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/anaconda
      export PATH="$HOME/anaconda/bin:$PATH"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-4.5.12-MacOSX-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p $HOME/anaconda
      export PATH="$HOME/anaconda/bin:$PATH"
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install openssl.light;
      choco install miniconda3 --params="'/AddToPath:1 /D:`cygpath --windows /c/tools/miniconda3/`'";
      export PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:$PATH";
    fi
  - conda env create -f environment.yml
  - source activate t-cell-image
  - conda list

script:
  # Need to run image_processing.ipynb to set up training images
  - jupyter-nbconvert --to notebook --inplace --execute image_processing.ipynb --ExecutePreprocessor.timeout=-1
  - travis_wait 50 jupyter-nbconvert --to notebook --inplace --execute $NOTEBOOK --ExecutePreprocessor.timeout=-1
