name: t-cell-image
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - ipython=7.2.0
  - jupyter=1.0.0
  - simplegeneric=0.8.1
  - python=3.6.8
  - r-base=3.5.1
  - r-ggplot2=3.0.0
  - r-ggpubr=0.2.0
  - libgfortran=3
  - rpy2=2.9.4
  - tzlocal=1.5.1
  - pip:
    - tensorflow==1.8.0
    - keras==2.1.6
    # Need a newer version of keras-vis
    # https://github.com/raghakot/keras-vis/issues/127
    - git+https://github.com/raghakot/keras-vis.git@137f268b77f40a12d373db17da74dcc9fe759680
    - matplotlib==3.0.2
    - numpy==1.15.0
    - scikit-image==0.14.1
    - scikit-learn==0.19.2
    - scipy==1.1.0
    - seaborn==0.9.0
    - tensorboard==1.8.0
    - umap-learn==0.3.8
    - opencv-python==4.0.0.21
    - pillow==5.3.0
    - h5py==2.8.0
    - pandas==0.24.0
