name: t-cell-image
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - ipython=7.2.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - python=3.6.8
  - r-base=3.5.1
  - tornado=5.1.1
  - pip:
    - keras==2.2.0
    - matplotlib==3.0.2
    - numpy==1.15.0
    - rpy2==2.9.5
    - scikit-image==0.14.1
    - scikit-learn==0.19.2
    - scipy==1.1.0
    - seaborn==0.9.0
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - umap==0.1.1
