name: Test notebooks
on:
- push
- pull_request
jobs:
  Test:
    name: Test notebooks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        #os: [ubuntu-latest, windows-latest, macos-latest]
        # Test notebooks in parallel
        notebook: [frequency_classifier.ipynb, logistic_regression.ipynb, simple_neural_network.ipynb, simple_cnn_lenet.ipynb, transfer_learning.ipynb]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: t-cell-image
          environment-file: environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      # Tests that the image processing notebook can execute in the conda environment
      - name: Execute image processing notebook
        shell: bash --login {0}
        run: jupyter-nbconvert --to notebook --inplace --execute image_processing.ipynb --ExecutePreprocessor.timeout=-1
      # Tests that the analysis notebooks can execute in the conda environment
      - name: Execute analysis notebook
        shell: bash --login {0}
        run: jupyter-nbconvert --to notebook --inplace --execute ${{ matrix.notebook }} --ExecutePreprocessor.timeout=-1
